name: GitHub Context and Variables

on: workflow_dispatch

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: To show github context
        run: echo "${{ toJson(github) }}"

  variables:
    runs-on: ubuntu-latest
    steps:
      - name: To show environment variable
        env:
          MY_NAME: ${{ vars.MY_NAME }}
          MY_ISSUE: ${{ secrets.MY_ISSUE }}
        run: |
          echo "My name is $MY_NAME"
          echo "My issue is $MY_ISSUE"
