name: workflows.yml

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  main-job:

    runs-on: temurin-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'sub-project/pom.xml'
      - name: Build with Maven
        run: mvn -B package --file pom.xml


  second-job:
    runs-on: temurin-lastest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: java exercice3bis.java

