name: workflows.yml

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  main-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'sub-project/pom.xml'

      - name: Build with Maven
        run: mvn -B package --file pom.xml


  second-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Compile exercice3bis.java
        run: javac exercice3bis.java

      - name: Run exercice3bis
        run: java exercice3bis
